### ISSUE TITLE
Server crash (MCForge 2443)

### ISSUE THREAD

**Issue by sharkck** [GirafiStudios/Ping#1]
The mod does not crash client-side but crashes server-side.

Here is the crash log and server log:
[2017-08-02-2.log-Ping.gz](https://github.com/dmillerw/Ping/files/1192862/2017-08-02-2.log-Ping.gz)

[crash-2017-08-02_02.20.29-server-Ping.txt](https://github.com/dmillerw/Ping/files/1192863/crash-2017-08-02_02.20.29-server-Ping.txt)

**Comment by GirafiStudios** [comment]
Thanks for your report!
Will be fixed in version 0.4.2, which should be out as soon as it gets approved on CurseForge :)

**Comment by sharkck** [comment]
Thank you!  Just got it loaded back in and all seems to be working fine!  Will open a new issue if I find anything further.
