### ISSUE TITLE
1.16.3 - Wrong FOV and ping location

### ISSUE THREAD

**Issue by AuracleTech** [GirafiStudios/Ping#17]
Plugin doesn't take FOV in consideration into the viewing angle of the ping, making the ping disappear on the side of the screen.
Also ping notification (the small icon pointing at the ping) when the ping is out of view is badly placed, it doesn't match the ping.
I will try to provide video of the issue (Or fix it myself if I have the courage)

Very nice plugin by the way 😊 hope this helps

Only thing I'd change is the ping HUD system, I'd make it like LoL (Quick action by keyup/keydown with different ping colors defending on the emergency)

**Comment by GirafiStudios** [comment]
Thank you for your feedback!
The issue off-screen ping indicator is a known issue, and have unfortunately always been a problem - I have attempted to fix it multiple times without luck. I tend to always see if I can find a solution everytime I move to a new major Minecraft version.
As for the FOV, as you can't change the FOV in vanilla (Unless they changed that recently?), I do not really have any desire to add support for this.
There is already Quick Pings on Keybinds. If I remember correctly it's Numpad 4-6 & Numpad 8
