### ISSUE TITLE
Log Spam

### ISSUE THREAD

**Issue by Thiana** [GirafiStudios/Ping#18]
This is an odd problem but I was able to find mention of it for another mod which helped me track it down to your mod.

Ping was recently added to the dev version of Enigmatica 6 and when I upgraded my local copy the following error started spamming my minecraft log multiple times per second.

```
[00:09:25] [Render thread/ERROR] [minecraft/MainWindow]: ########## GL ERROR ##########
[00:09:25] [Render thread/ERROR] [minecraft/MainWindow]: @ Pre render
[00:09:25] [Render thread/ERROR] [minecraft/MainWindow]: 65539: Invalid key -1
```

For some reason the default key for Ping is undefined and as long as it stays that way the error continues. If I set the keybinding the error stops until I reset the key. The issue that helped my isolate this error to ping can be seen here: https://github.com/RobertSkalko/Mine-and-Slash/issues/95

Thanks.

**Comment by GirafiStudios** [comment]
What version of Ping are you using?

**Comment by Thiana** [comment]
Oops, forgot the details on the environment:

Ping-1.16.4-1.6.8
Forge 35.1.37
Minecraft 1.16.4

**Comment by Thiana** [comment]
Enigmatic 6 is available here: https://github.com/NillerMedDild/Enigmatica6/commits/develop

I'm running on the develop branch.

**Comment by GirafiStudios** [comment]
The fact that the keybinds is not set, must be done by the Enimgatica 6 modpacker creator.
That it was throwing errors was definetly on my side, I'll get a new build on CurseForge right away :)

**Comment by Thiana** [comment]
Thank you :)

**Comment by NielsPilgaard** [comment]
I did indeed unbind it. Thanks for the quick fix :D
