### ISSUE TITLE
Ping Does Not Support Full MC Controls Range

### ISSUE THREAD

**Issue by ghost** [GirafiStudios/Ping#19]
`Minecraft 1.16.4`
`Forge 35.1.37`
`Ping 1.6.9`

According to the [list of MC-supported key codes](https://minecraft.gamepedia.com/Key_codes), there is the ability to bind things to keys F13-F25. I would like to utilise this for the modpack I am developing, to get around GirafiStudios/MineMenu#94 without using up 'real' keyboard binds (as I can't afford to with 220+ mods...).

However, when using these keybindings, Ping simply doesn't respond at all to the buttons being pressed (I have a program that emulates these keypresses, and I know Minecraft receives them correctly because I can set the keybinds this way in the controls menu), or from MineMenu attempting to trigger them via `ping.key.<mine/look/goto/alert>`.

**Comment by ghost** [comment]
Note: It's hard for me to tell whether this is a symptom of #20, or an independent issue. I hope you may have more insight than I do!

**Comment by GirafiStudios** [comment]
I've just tested all the F13-F24 (Can't do F25 with what I have, so can't test it) using Logitech G HUB and it was working perfectly fine. Sounds like something is wrong with the software you use to emulate the keypresses. Or that you have not changed it in your controls options, maybe?

**Comment by ghost** [comment]
I feel as if it wouldn't be the software, considering Minecraft itself registers those inputs just fine (for example, when assigning them in the controls options)? If Minecraft can recognise them, why can't Ping?

**Comment by GirafiStudios** [comment]
Have you tried making those keys trigger any vanilla keybinds?

**Comment by ghost** [comment]
Just tried it with the jump control set to F13 - it worked without issue.

**Comment by GirafiStudios** [comment]
Have you tried F13-F24 after reinstalling Ping, as you mentioned in the other issue?
Also just to be clear are you attempting to use it for the quick pings or the ping menu?

**Comment by ghost** [comment]
Quick pings. No, I haven't tried that yet, I'll do so when I next get the chance!
