### ISSUE TITLE
Causes PortalGun to only render one portal at a time

### ISSUE THREAD

**Issue by Jomik** [GirafiStudios/Ping#2]
Chun suggested you may be doing something funny 😄 

https://github.com/iChun/IssueTracker-Mods/issues/124

This happens with just Ping! and PortalGun installed, no selection menu and no active pings.

**Comment by GirafiStudios** [comment]
Does it happen when no Pings are active and without the ping selection menu up? ^^

**Comment by Jomik** [comment]
Apologies for a lacking description. Updated.

**Comment by GirafiStudios** [comment]
It does indeed happen, and only when Ping is installed.
I will try to look into it, but to be honest I have no clue what could be causing this.

**Comment by GirafiStudios** [comment]
@Jomik I have responded with my discoveries about the issue on iChun's issue tracker. I will let the discussion continue over there instead, so iChun and I hopefully can figure out a solution to the problem.
