### ISSUE TITLE
Individual Ping Type Keybinds Fail

### ISSUE THREAD

**Issue by ghost** [GirafiStudios/Ping#20]
`Minecraft 1.16.4`
`Forge 35.1.37`
`Ping 1.6.9`

Even with the default keybinds, no pings occur when those buttons are pressed. Nothing appears in the logs, and there is no crash. Let me know if you'd like to see the logs anyway!

**Comment by GirafiStudios** [comment]
I've just tested with those exact versions that you've specified and all quick pings keybinds (Or Individual Ping Types keybinds, as you call them) do all occur. You most likely have another mod that conflicts with those keybinds.
I would recommend installing the mod called "Controlling" to easier identify keybind conflicts.

**Comment by ghost** [comment]
I have controlling installed - there are no conflicting keybinds and the mod still refuses to respond to those keypresses. They're nothing special, in fact, they are the defaults, and despite no conflicts, they do not work.

I should add that "Open Ping Menu" works fine, but assigning literally any key to the individual controls does nothing.

**Comment by ghost** [comment]
After reinstalling Ping, the individual keys now work! Still at a loss as to why it broke in the first place...
