### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by Looodon** [GirafiStudios/Ping#26]
Hey,
Will this mod ever be compatible with shaders?
Thanks!

**Comment by Looodon** [comment]
I just downloaded the 1.19.2 version of the mod and it doesnt work with shaders

**Comment by GirafiStudios** [comment]
To my knowledge there is nothin I can do to make it compatible.

**Comment by Looodon** [comment]
A mod called [Ping Wheel](https://www.curseforge.com/minecraft/mc-mods/ping-wheel) made for fabric only does. The mod maker said that the mod was inspired by your mod. Maybe looking into that mod might help fix the issue since it allows for pinging even with shaders
