### ISSUE TITLE
Icon too small and appear on the wrong side when out of screen

### ISSUE THREAD

**Issue by domanhthang2110** [GirafiStudios/Ping#27]
When I ping a block then turn away the icon sometimes appear on the opposite side of my screen instead of the side of the ping.
Also I can't find a comment section or discord so I will leave my suggestion here:
- Make the icon bigger when it's in sight (and out too) since it's pretty hard to spot a red block far away, it should scale to the screen size regardless of distance imo
- Increase the ping distance
- Make the ping selection closer to the center for faster pinging. A radial menu would be the best like each icon in 4 side

**Comment by GirafiStudios** [comment]
Ping distance can be changed in the config.
There is keybinds for quick pings.
Strongly disagree with making the ping icon bigger.

You're Indeed correct that the off screen pings are broken, they unfortunately always have been wonky.
Tried to fix it many times without luck.
