### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by CaptFarosh** [GirafiStudios/Ping#28]
Is there a way to adjust the maximum distance that I can ping? I tried adjusting in the config file and it keeps resetting the maximum to 255. Also is there a way to replace the ping sound via a resource pack? Thanks!

**Comment by GirafiStudios** [comment]
Make sure the game is closed, when you edit the config.
Yes, you can change the Ping sound with a resourcepack. Look up how to do it in vanilla.

**Comment by CaptFarosh** [comment]
The game was closed, it still reset to 255. Also I was asking more what is the file path for the ping. I've made several resourcepacks before. Thanks!

**Comment by GirafiStudios** [comment]
Same path as for any sound, just use the mod namespace instead.
For excact path, you can check here on Github!
