### ISSUE TITLE
[1.7.10] Ping invisible on big distances

### ISSUE THREAD

**Issue by nitwhiz** [GirafiStudios/Ping#3]
Would it be possible to have a minimum size for the displayed ping?

..and more or less off-topic, is it possible to build the current source against 1.7.10?

**Comment by GirafiStudios** [comment]
That is intended behavior, and can be changed in the config.
There is a 1.7.10 branch that is possible to build yes, but the latest source is not possible to build against for 1.7.10 no.

**Comment by nitwhiz** [comment]
But there is no setting for size and it's not fetched in the code anywhere as far as i saw?

**Comment by GirafiStudios** [comment]
Oh I misunderstood what you said.
The distance at which you can "set" a ping can be changed in the config. As for the distance you can see a Ping, is only limited by your render distance.

**Comment by nitwhiz** [comment]
Yeah of course. It's more a problem of scaling, i set up the maximum distance already.
But at a distance where you just want to ping "i am here!" its like a single pixel or so..
