### ISSUE TITLE
Ping-fabric-1.20.4-1.11.1 = Crash. (Forge Config API Port is required)

### ISSUE THREAD

**Issue by Zorklis** [GirafiStudios/Ping#32]
[crash-2023-12-31_04.20.38-client.txt](https://github.com/GirafiStudios/Ping/files/13800026/crash-2023-12-31_04.20.38-client.txt)

**Comment by GirafiStudios** [comment]
You don´t have Forge Config API Port installed, which is required for the Fabric version of Ping :)

**Comment by Zorklis** [comment]
Oh, it doesn't notify us that's required (that should be fixed). Thanks

**Comment by GirafiStudios** [comment]
Oh you´re right. Forgot it for just Ping when updating my mods apparently. Corrected in dev now. Thanks!
