### ISSUE TITLE
Replacing keybind does nothing

### ISSUE THREAD

**Issue by Zorklis** [GirafiStudios/Ping#33]
So by default V is Ping, but I want Nimble mod (to turn on front view) to be V, 
so I changed Nimble to V key and Ping key to be X, 
yet the ping menu still pops up with V and pressing X does not turn on the Ping menu.
tl:dr ping keybinding is broken

**Comment by GirafiStudios** [comment]
What version of Minecraft and Ping are you on?

**Comment by Zorklis** [comment]
Ping-fabric-1.20.4-1.11.1 , so Fabric and on 1.20.4

**Comment by Zorklis** [comment]
Tested out the new release "Ping-fabric-1.20.4-1.11.2", seems fixed, thanks
