### ISSUE TITLE
Not working on neoforge

### ISSUE THREAD

**Issue by wilczany** [GirafiStudios/Ping#35]
Tried using it on neoforge. The menu shows up, but nothing happens after using it.

Minecraft : 1.20.4
Neoforge: 20.4.232
Mod: 1.12.2

**Comment by GirafiStudios** [comment]
Install (or update) Common Network by Mysticdrew :)

**Comment by wilczany** [comment]
This resolved the issue, but only on singleplayer. When I try to use it in multiplayer the same thing happens.

**Comment by GirafiStudios** [comment]
I updated Ping aswell, have you tried the new version?

**Comment by wilczany** [comment]
yes, I did

**Comment by GirafiStudios** [comment]
Did you update the Ping version on the server as well?

**Comment by wilczany** [comment]
Yes,  also
