### ISSUE TITLE
Player pings not showing for other players 

### ISSUE THREAD

**Issue by miyoshikai** [GirafiStudios/Ping#36]
NeoForge-20.4.235 (1.20.4)

When a player pings, their pings do not show to other players.

My guess was it had to do with the "Chosen to receive Pings" function, but I don't see a setting for that anywhere.

The players are all next to each other, and no matter where the players ping, it will not show for the other players.

**Comment by GirafiStudios** [comment]
Is Ping installed on the server as well?

If yes, are the players using any shaders by chance?

**Comment by GirafiStudios** [comment]
Also what version of Ping are you using?
