### ISSUE TITLE
Ping doesn't render on Fabulous graphics

### ISSUE THREAD

**Issue by OddyUlrich** [GirafiStudios/Ping#37]
Don't ask me how or why. But I tried using only Ping with neoforge 21.0.95-beta in the Prism Launcher 8.4 and I can't see any ping. But if I use the original minecraft Launcher I can...
At first I thought it was my other mods, but I removed all of them except this one and still didn't work. Maybe I'm doing something wrong, but I really don't understand how it is possible.

EDIT: I'm stupid. If you use "Graphics: Fabulous!" The pings will "not render". When I changed them to "Fancy" all was good... I'm sorry.

**Comment by GirafiStudios** [comment]
I missed this completely somehow, sorry about that!

It's a bug, that it doesn't render on Fabulous graphics - I'll have to look into that.
