### ISSUE TITLE
Spigot compatibility

### ISSUE THREAD

**Issue by VariableVixen** [GirafiStudios/Ping#4]
I know that this mod needs to send information to the server, which must then send it out to other clients, in order to actually transmit the pings to people. The thing is, I'm running a spigot server. I'd really love to have this mod, so is there any 1.12.2 Spigot plugin that would send out the received packets so I could still use this mod? If not, would it be reasonably possible to make one?

**Comment by GirafiStudios** [comment]
I have no knowledge about how Spigot works, so unfortunately not much I can do here.
If you figure out a solution, please let me know :)

**Comment by VariableVixen** [comment]
Alright, I'm working on a simple "packet forwarder" plugin now. If all goes well, it'll be able to send non-vanilla packets to connected clients.
