### ISSUE TITLE
Keybinds other than Ping Menu reset on startup

### ISSUE THREAD

**Issue by khionu** [GirafiStudios/Ping#5]
Every time I start up my pack, the other 4 keybinds are reset. It's the only mod in the pack that's doing this, so I assume it's a bug.

Currently on 1.4.3 for 1.12.2, using forge version 14.23.4.2747

**Comment by GirafiStudios** [comment]
Thank you for your report!
Fixed now. A new version will be out on CurseForge, as soon as they approve it.

**Comment by khionu** [comment]
Thank you very much for the speed of the patch!
