### ISSUE TITLE
holding down the ping button glitches it

### ISSUE THREAD

**Issue by colemy** [GirafiStudios/Ping#9]
in v1.6.1 holding down the ping (go to) button causes it to be spammed and then it no longer works for a few seconds and not until after a different key has been pressed

**Comment by GirafiStudios** [comment]
Thank you for you report!
I've actually that on purpose, because of how Minecraft's keybinding system works. It have no way of not making a key continuously be called when held down (Try to keep holding E for example).
But I can make it just be possible to spam it forever, if that's prefered?

**Comment by colemy** [comment]
> Thank you for you report!
> I've actually that on purpose, because of how Minecraft's keybinding system works. It have no way of not making a key continuously be called when held down (Try to keep holding E for example).
> But I can make it just be possible to spam it forever, if that's prefered?

yea i guess its just a minecraft issue, maybe leave mojang a ticket on their website because that is really poor game design lol

**Comment by GirafiStudios** [comment]
It is a known issue since they moved to LWGL 3 in 1.13. Been reported many times.
Can't really do anything besides hope they fix it (If they even can)
